config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'

  resources :posts do
	  resources :comments
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to = :Posts
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
		@title = 'my first about page'; 
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def new
		@post =Post.new
	end

	def destroy
	  @post = Post.find(params[:id])
	  @post.destroy
	 
	  redirect_to posts_path
	end

	def update
	  @post = Post.find(params[:id])
	 
	  if @post.update(params[:post].permit(:title, :text))
	    redirect_to @post
	  else
	    render 'edit'
	  end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def show
	  @post = Post.find(params[:id])
	end

	def create
	  @post = Post.new(params[:post].permit(:title, :text))
	 
	  if @post.save
	    redirect_to @post
	  else
	    render 'new'
	  end
	end

	private
	  def post_params
	    params.require(:post).permit(:title, :text)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Rails App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="home">SimpleRails App</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create Post", new_post_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container-fluid">
    	<%= yield %>
    </div>
    <hr>
    <div class="container">
        <footer>
        <p>&copy; 2018 Company, Inc.</p>
      </footer>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is <%= @title %></h1>

app/views/posts/_form-comment.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field(:commenter, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/_form.html.erb
<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:text, {:class => 'form-control'}) %>
  </p>
 
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
    <%= link_to 'Back', posts_path, :class => 'btn btn-default' %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>

<%= render 'form' %>
 

app/views/posts/index.html.erb
<div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><%= link_to "Create Post", new_post_path, :class => 'btn btn-primary btn-lg' %></p>
      </div>
    </div>
<% @posts.each do |post| %>
    <div class="well">
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
    <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
    <%= link_to 'Destroy', post_path(post),
                    method: :delete, 
                    data: { confirm: 'Are you sure?'},
                    :class => 'btn btn-danger' %>

    </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Posts</h1>

<%= render 'form' %>
 

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.text %></p>
<%= link_to 'Back', posts_path, :class => 'btn btn-default' %>
<%= link_to 'Edit', edit_post_path(@post),({:class => 'btn btn-primary'}) %>
<hr>
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>
<hr>
<h2>Add a comment:</h2>
<%= render 'form-comment' %>